const RSSI_THRESHOLDS = {
  VERY_CLOSE: -40,
  CLOSE: -55,
  MEDIUM: -70,
  FAR: -85,
  VERY_FAR: -100,
};

const DEFAULT_RSSI_THRESHOLD = -70;
const DEFAULT_LOCK_DELAY_SEC = 10;
const SCAN_INTERVAL_MS = 3000;

module.exports = { RSSI_THRESHOLDS, DEFAULT_RSSI_THRESHOLD, DEFAULT_LOCK_DELAY_SEC, SCAN_INTERVAL_MS };
